version: '1'
services:
  sign-up-service:
    build:
      context: .
      dockerfile: ./signUpService/Dockerfile
    ports:
      - 5190:5190
    networks:
      - banking_net
      - elastic

  sign-in-service:
    build:
      context: .
      dockerfile: ./signInService/Dockerfile
    ports:
      - 5191:5191
    networks:
      - banking_net
      - elastic

  sign-out-service:
    build:
      context: .
      dockerfile: ./signOutService/Dockerfile
    ports:
      - 5192:5192
    networks:
      - banking_net
      - elastic

  train-model-service:
    build:
      context: .
      dockerfile: ./trainModelService/Dockerfile
    ports:
      - 5193:5193
    networks:
      - banking_net
      - elastic
      
  predict-transaction-service:
    build:
      context: .
      dockerfile: ./predictTransactionService/Dockerfile
    ports:
      - 5194:5194
    networks:
      - banking_net
      - elastic

  manage-model-service:
    build:
      context: .
      dockerfile: ./ManageModelService/Dockerfile
    ports:
      - 5195:5195
    networks:
      - banking_net
      - elastic


networks:
  banking_net:
    name: banking_net

  elastic:
    external: true
      