version: '1'
services:
  sing-up-service:
    build:
      context: .
      dockerfile: ./singUpService/Dockerfile
    ports:
      - 5190:5190
    networks:
      - banking_net
      - elastic

  sing-in-service:
    build:
      context: .
      dockerfile: ./singInService/Dockerfile
    ports:
      - 5191:5191
    networks:
      - banking_net
      - elastic

  sing-out-service:
    build:
      context: .
      dockerfile: ./singOutService/Dockerfile
    ports:
      - 5192:5192
    networks:
      - banking_net
      - elastic

  train-model-service:
    build:
      context: .
      dockerfile: ./trainModelService/Dockerfile
    ports:
      - 5193:5193
    networks:
      - banking_net
      - elastic
      
  predict-transaction-service:
    build:
      context: .
      dockerfile: ./predictTransactionService/Dockerfile
    ports:
      - 5194:5194
    networks:
      - banking_net
      - elastic

  manage-model-service:
    build:
      context: .
      dockerfile: ./ManageModelService/Dockerfile
    ports:
      - 5195:5195
    networks:
      - banking_net
      - elastic


networks:
  banking_net:
    name: banking_net

  elastic:
    external: true
      